FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/nginx:1.19

ARG TARGETARCH

WORKDIR /run

COPY entrypoint.sh /run/entrypoint.sh
COPY resource-proxy.conf /etc/nginx/conf.d/

VOLUME ["/data/nginx/cache"]

RUN chmod +x /run/entrypoint.sh
ENTRYPOINT [ "/run/entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]