FROM nginx:1.19
ARG RELEASE_DESC
ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
COPY resource-proxy.conf /etc/nginx/conf.d/

VOLUME ["/data/nginx/cache"]
ENV RELEASE_DESC=${RELEASE_DESC}

RUN chmod +x /run/entrypoint.sh
ENTRYPOINT [ "/run/entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]