FROM --platform=${TARGETPLATFORM} swr.cn-southwest-2.myhuaweicloud.com/wutong/golang4wtall:1.15 as builder
ARG TARGETOS TARGETARCH TARGETPLATFORM

WORKDIR /workspace
ENV GOPROXY=https://goproxy.cn

COPY go.mod go.mod
COPY go.sum go.sum

COPY api/ api/
COPY builder/ builder/
COPY cmd/ cmd/
COPY db/ db/
COPY discover/ discover/
COPY discover.v2/ discover.v2/
COPY event/ event/
COPY eventlog/ eventlog/
COPY gateway/ gateway/
COPY grctl/ grctl/
COPY monitor/ monitor/
COPY mq/ mq/
COPY node/ node/
COPY pkg/ pkg/
COPY util/ util/
COPY webcli/ webcli/
COPY worker/ worker/

COPY build-wtall.sh build-wtall.sh

COPY vendor/ vendor/
# RUN go mod vendor

ENV GO111MODULE=on TARGETOS=${TARGETOS} TARGETARCH=${TARGETARCH}
RUN mkdir /output/bin -p && ./build-wtall.sh

FROM --platform=${TARGETPLATFORM} wutongpaas/alpine:3.15
ARG TARGETOS TARGETARCH TARGETPLATFORM
RUN mkdir /output/bin -p && chmod 777 /output/bin

COPY --from=builder /output/bin/ /output/bin/