ARG VERSION
ARG IMAGE_REPO
FROM --platform=${TARGETPLATFORM} ${IMAGE_REPO}/wt-all:${VERSION} AS wt-all

FROM --platform=${TARGETPLATFORM} wutongpaas/openresty:1.19.3.2-alpine
ARG RELEASE_DESC
ARG TARGETOS TARGETARCH TARGETPLATFORM

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk add --no-cache bash net-tools curl tzdata && \
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
        echo "Asia/Shanghai" >  /etc/timezone && \
        date && apk del --no-cache tzdata

ADD . /run
COPY --from=wt-all /output/bin/wutong-gateway /run/wutong-gateway

RUN set -eux; \
    if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then \
        wget https://wutong-paas-public.obs.cn-east-3.myhuaweicloud.com/arm/1.0/librestychash.so -O /run/nginx/lua/vendor/so/librestychash.so; \
    fi

ENV NGINX_CONFIG_TMPL=/run/nginxtmp
ENV NGINX_CUSTOM_CONFIG=/run/nginx/conf
ENV RELEASE_DESC=${RELEASE_DESC}
ENV OPENRESTY_HOME=/usr/local/openresty
ENV PATH="${PATH}:${OPENRESTY_HOME}/nginx/sbin"
EXPOSE 8080

ENTRYPOINT ["/run/entrypoint.sh"]