FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/alpine:3.15
ARG RELEASE_DESC
ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
RUN mkdir /root/.kube

ENV PORT 7070

ENV RELEASE_DESC=${RELEASE_DESC}
ENTRYPOINT ["/run/entrypoint.sh"]