FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/wt-chaos-base:stable

ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
COPY export-app /src/export-app

ENTRYPOINT ["/run/entrypoint.sh"]