FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/wt-mesh-data-panel-base:stable-envoyv1.32.1

ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
COPY envoy_config.yaml /run/envoy_config.yaml

RUN chmod 755 /run/entrypoint.sh

ENTRYPOINT ["/run/entrypoint.sh"]