FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/alpine:3.15

ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh

RUN chmod 655 /run/wutong-init-probe /run/entrypoint.sh

ENTRYPOINT [ "/run/entrypoint.sh" ]
CMD ["probe"]