FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/wt-eventlog-base:stable
ARG RELEASE_DESC
ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
COPY build/libzmq/lib/libzmq.so.3 /tmp

RUN if [ ${TARGETARCH} = "amd64" ]; then \
        cp /tmp/libzmq.so.3 /usr/lib/libzmq.so.3 && rm /tmp/libzmq.so.3; \
    fi

EXPOSE 6366
EXPOSE 6365
EXPOSE 6364
EXPOSE 6363
EXPOSE 6362
EXPOSE 6607
ENV RELEASE_DESC=${RELEASE_DESC}
ENTRYPOINT  ["/run/entrypoint.sh"]
