FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/alpine:3.15
ARG RELEASE_DESC
ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh
COPY build/libzmq/lib/libzmq.so.3 /tmp

RUN if [ $(uname -m) = "aarch64" ]; then \
        apk add --no-cache libstdc++ ca-certificates openssl openssl-dev zeromq-dev; \
    else \
        cp /tmp/libzmq.so.3 /usr/lib/libzmq.so.3 && rm /tmp/libzmq.so.3 && apk add --no-cache libstdc++ ca-certificates openssl openssl-dev; \
    fi
    
EXPOSE 6366
EXPOSE 6365
EXPOSE 6364
EXPOSE 6363
EXPOSE 6362
EXPOSE 6607
ENV RELEASE_DESC=${RELEASE_DESC}
ENTRYPOINT  ["/run/entrypoint.sh"]
