FROM debian:buster
ARG RELEASE_DESC
      
RUN apt-get update && apt-get install -y ca-certificates openssl libssl-dev libsodium-dev libpgm-dev libnorm-dev libgssapi-krb5-2 wget
    
RUN wget https://wutong-paas.obs.cn-east-3.myhuaweicloud.com/arm/libzmq.so.5 -O /usr/lib/libzmq.so.5
    
COPY wutong-eventlog /run/wutong-eventlog
ADD entrypoint.sh /run/entrypoint.sh
    
EXPOSE 6366
EXPOSE 6365
EXPOSE 6364
EXPOSE 6363
EXPOSE 6362
VOLUME [ "/etc/wutongpaas" ]
ENV RELEASE_DESC=${RELEASE_DESC}
ENTRYPOINT  ["/run/entrypoint.sh"]