ARG BASE_IMAGE_VERSION
ARG VERSION
ARG IMAGE_REPO
FROM --platform=${TARGETPLATFORM} ${IMAGE_REPO}/wt-all:${VERSION} AS wt-all

FROM --platform=${BUILDPLATFORM} wutongpaas/alpine:${BASE_IMAGE_VERSION}
ARG RELEASE_DESC
ARG TARGETOS TARGETARCH TARGETPLATFORM

COPY . /run
COPY --from=wt-all /output/bin/wutong-grctl /run/wutong-grctl

RUN chmod +x /run/wutong-grctl /run/entrypoint.sh
VOLUME [ "/rootfs/root","/rootfs/path","/ssl" ]
ENV RELEASE_DESC=${RELEASE_DESC}
ENTRYPOINT ["/run/entrypoint.sh"]