region_api:
    endpoints:
      - https://region.wutong.me:8443
    client-ca-file: /opt/wutong/etc/wt-api/region.wutong.me/ssl/ca.pem
    tls-cert-file:  /opt/wutong/etc/wt-api/region.wutong.me/ssl/client.pem
    tls-private-key-file:  /opt/wutong/etc/wt-api/region.wutong.me/ssl/client.key.pem