FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/prometheus:v2.20.0

ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh

USER root
VOLUME ["/prometheusdata"]

ENTRYPOINT ["/run/entrypoint.sh"]