FROM swr.cn-southwest-2.myhuaweicloud.com/wutong/alpine:3.15

ARG TARGETARCH

WORKDIR /run

COPY ${TARGETARCH}/ /run/
COPY entrypoint.sh /run/entrypoint.sh

RUN chmod +x /run/wutong-wtctl /run/entrypoint.sh

VOLUME [ "/rootfs/root","/rootfs/path","/ssl" ]

ENTRYPOINT ["/run/entrypoint.sh"]