// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: event_log.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventLog_Log_FullMethodName = "/pb.EventLog/Log"
)

// EventLogClient is the client API for EventLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventLogClient interface {
	Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogMessage, Reply], error)
}

type eventLogClient struct {
	cc grpc.ClientConnInterface
}

func NewEventLogClient(cc grpc.ClientConnInterface) EventLogClient {
	return &eventLogClient{cc}
}

func (c *eventLogClient) Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogMessage, Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventLog_ServiceDesc.Streams[0], EventLog_Log_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogMessage, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventLog_LogClient = grpc.ClientStreamingClient[LogMessage, Reply]

// EventLogServer is the server API for EventLog service.
// All implementations must embed UnimplementedEventLogServer
// for forward compatibility.
type EventLogServer interface {
	Log(grpc.ClientStreamingServer[LogMessage, Reply]) error
	mustEmbedUnimplementedEventLogServer()
}

// UnimplementedEventLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventLogServer struct{}

func (UnimplementedEventLogServer) Log(grpc.ClientStreamingServer[LogMessage, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedEventLogServer) mustEmbedUnimplementedEventLogServer() {}
func (UnimplementedEventLogServer) testEmbeddedByValue()                  {}

// UnsafeEventLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventLogServer will
// result in compilation errors.
type UnsafeEventLogServer interface {
	mustEmbedUnimplementedEventLogServer()
}

func RegisterEventLogServer(s grpc.ServiceRegistrar, srv EventLogServer) {
	// If the following call pancis, it indicates UnimplementedEventLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventLog_ServiceDesc, srv)
}

func _EventLog_Log_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventLogServer).Log(&grpc.GenericServerStream[LogMessage, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventLog_LogServer = grpc.ClientStreamingServer[LogMessage, Reply]

// EventLog_ServiceDesc is the grpc.ServiceDesc for EventLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventLog",
	HandlerType: (*EventLogServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Log",
			Handler:       _EventLog_Log_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event_log.proto",
}
