ARG VERSION
ARG IMAGE_REPO
FROM --platform=${TARGETPLATFORM} ${IMAGE_REPO}/wt-all:${VERSION} AS wt-all

FROM --platform=${TARGETPLATFORM} wutongpaas/alpine:3.15
ARG RELEASE_DESC
ARG TARGETOS TARGETARCH TARGETPLATFORM

COPY --from=wt-all /output/bin/wutong-api /run/wutong-api
ADD entrypoint.sh /run/entrypoint.sh
WORKDIR /run
ENV RELEASE_DESC=${RELEASE_DESC}
VOLUME [ "/etc/wutongpaas" ]
ENTRYPOINT ["/run/entrypoint.sh"]