name: amd64-build

on:
  push:
    branches: [v1.4.0]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to myhuaweicloud-swr
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOMESTIC_DOCKER_SERVER }}
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Release
        run: ./amd64-build.sh