name: release

on:
  release:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to myhuaweicloud-swr
        uses: docker/login-action@v1
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Build the Docker image
        env:
          VERSION: v1.3.0
        run: |
          go mod vendor
          ./release.sh all push
