name: release-swr

on:
  release:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to myhuaweicloud-swr
        uses: docker/login-action@v1
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }} 

      - name: Build the Docker image
        env:
          IMAGE_REPO: swr.cn-southwest-2.myhuaweicloud.com/wutong
          VERSION: v1.0.0-stable
        run: ./release-new.sh
